name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-2-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-2-

      - uses: actions/cache@v3
        name: Setup cypress cache
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-pnpm-store-2-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Lint check
        run: pnpm run lint
      
      - name: Build
        run: pnpm run build

      - name: Start server and wait
        run: pnpm run start-wait
      
      - name: End-to-end testing
        run: pnpm run cy:run

      - name: Export static files
        run: pnpm run export

      - name: Sync htaccess & clear files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp01.binero.se
          username: 166107_github
          password: ${{ secrets.ftp_password }}
          dangerous-clean-slate: true
          local-dir: ./upload/

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp01.binero.se
          username: 166107_github
          password: ${{ secrets.ftp_password }}
          local-dir: ./out/

      
