name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      
      - name: Npm Continuous Integration install
        run: npm ci

      - name: Lint check
        run: npm run lint
      
      - name: Build
        run: npm run build

      - name: Start server and wait
        run: npm run start-wait
      
      - name: End-to-end testing
        run: npm run cy:run

      - name: Export static files
        run: npm run export

      - name: Sync htaccess & clear files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp01.binero.se
          username: 166107_github
          password: ${{ secrets.ftp_password }}
          dangerous-clean-slate: true
          local-dir: ./upload/

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp01.binero.se
          username: 166107_github
          password: ${{ secrets.ftp_password }}
          local-dir: ./out/

      
